name: Pylint

on:
  pull_request:
    branches: [main] # or whichever branches you want to lint on PRs

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # adjust to your version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          # include your own project deps if needed:
          # pip install -r requirements.txt

      - name: Run Pylint
        run: pylint $(git ls-files '*.py') --fail-under=8.0
